/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sysmon.agent;

import org.apache.camel.main.Main;

public class Application {

    public static void main(String[] args) {

        // use Camels Main class
        Main main = new Main();

        // and add the routes (you can specify multiple classes)
        main.configure().addRoutesBuilder(MyRouteBuilder.class);

        // now keep the application running until the JVM is terminated (ctrl + c or sigterm)
        try {
            main.run(args);
        } catch(Exception e) {
            System.err.println(e.getMessage());
        }

    }
}
