###
### Sysmon Client
###
### Example configuration with default values.
###

[extension.base_info]
enabled = true
interval = '60m'

[extension.base_disk]
enabled = true

[extension.base_filesystem]
enabled = true
exclude_type = [ "tmpfs", "ahafs" ]
exclude_mount = [ "/boot/efi" ]

[extension.base_process]
enabled = true
include = [
    "java", "node", "httpd", "mongod", "mysqld",
    "postgres", "influxd", "haproxy", "beam.smp",
    "filebeat", "corosync", "rsyslogd", "memcached",
    "db2sysc", "dsmserv", "mmfsd",
]
