###
### Sysmon Client
###
### Example configuration with some default values.
###

# Sysmon Server URL
server = "http://127.0.0.1:9925/metrics"

# Override hostname
#hostname = "cattle1"

# Local path containing plugins
plugins = "/opt/sysmon/plugins"

# Local path for Groovy scripts
scripts = "/opt/sysmon/scripts"

[extension.base_info]
enabled = true
interval = '60m'

[extension.base_disk]
enabled = true
interval = '10s'

[extension.base_filesystem]
enabled = true
interval = '10s'
exclude_type = [ "tmpfs", "ahafs" ]
exclude_mount = [ "/boot/efi" ]

[extension.base_process]
enabled = true
interval = '5m'
include = [
    "java", "node", "httpd", "mongod", "mysqld",
    "postgres", "influxd", "haproxy", "beam.smp",
    "filebeat", "corosync", "rsyslogd", "memcached",
    "db2sysc", "dsmserv", "mmfsd",
]
