{
 "title": "Sysmon - Process Explorer",
 "description": "Metrics from within host / guest / partition.",
 "time": { "from": "now-3h", "to": "now-30s" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"base_memory\" WITH KEY = \"hostname\" WHERE time > now() - 60m"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "SHOW TAG VALUES FROM \"base_process\" WITH KEY = \"name\" WHERE hostname =~ /$hostname/AND time > now() - 60m"
   },
   {
    "name": "pid",
    "label": "PID",
    "query": "SHOW TAG VALUES FROM \"base_process\" WITH KEY = \"pid\" WHERE hostname =~ /$hostname/AND \"name\" =~ /$process/ AND time > now() - 60m"
   }
  ]
 },
 "panels": [
  { "title": "${hostname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Details",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "base_process",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "group" ], "type": "field" },
       { "params": [ "group" ], "type": "alias" }
      ],
      [
       { "params": [ "path" ], "type": "field" },
       { "params": [ "path" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$process$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "select": [
      [
       { "params": [ "mem_rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "rss" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_virt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "virt" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$process$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Metrics",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$process$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "query": "SELECT non_negative_difference(sum(last(\"user_time\"),last(\"kernel_time\"))) FROM \"base_process\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "user_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "kernel_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "kernel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$process$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads & Open Files",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "query": "SELECT sum(non_negative_derivative(mean(\"user_time\"), 30s), non_negative_derivative(mean(\"user_time\"), 30s))  FROM \"base_process\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "files" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "files" ], "type": "alias" }
      ],
      [
       { "params": [ "threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "threads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$process$/" },
      { "condition": "AND", "key": "pid", "operator": "=~", "value": "/^$pid$/" }
     ]
    }
   ]
  }
 ]
}