{
 "title": "Sysmon - Host Overview",
 "description": "https://bitbucket.org/mnellemann/sysmon/ - Metrics from sysmon agent.",
 "tags": [ "sysmon" ],
 "time": { "from": "now-24h", "to": "now-10s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"base_memory\" WITH KEY = \"hostname\" WHERE time > now() - 60m"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Metrics are collected by an agent running inside of each LPAR / VM / Host.\n    \n  For more information: [bitbucket.org/mnellemann/sysmon](https://bitbucket.org/mnellemann/sysmon)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Information",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "text" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "100",
     "measurement": "base_info",
     "query": "SELECT last(\"os_manufacturer\") AS \"manufacturer\", last(\"os_family\") AS \"family\", last(\"os_version\") AS \"version\",  last(\"os_codename\") AS \"codename\", last(\"os_build\") AS \"build\", last(\"boot_time\") * 1000 AS \"boottime\" FROM \"base_info\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\" fill(null) ORDER BY time DESC LIMIT 1000",
     "select": [
      [
       { "params": [ "os_manufacturer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "manufacturer" ], "type": "alias" }
      ],
      [
       { "params": [ "os_family" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "family" ], "type": "alias" }
      ],
      [
       { "params": [ "os_codename" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "codename" ], "type": "alias" }
      ],
      [
       { "params": [ "os_build" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "build" ], "type": "alias" }
      ],
      [
       { "params": [ "os_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "version" ], "type": "alias" }
      ],
      [
       { "params": [ "boot_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "boottime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "base_load",
     "select": [
      [
       { "params": [ "1min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1min" ], "type": "alias" }
      ],
      [
       { "params": [ "5min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5min" ], "type": "alias" }
      ],
      [
       { "params": [ "15min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Details (IBM Power)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aix_processor",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mode" ], "type": "alias" }
      ],
      [
       { "params": [ "type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "type" ], "type": "alias" }
      ],
      [
       { "params": [ "ent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ent" ], "type": "alias" }
      ],
      [
       { "params": [ "lcpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "lcpu" ], "type": "alias" }
      ],
      [
       { "params": [ "smt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "smt" ], "type": "alias" }
      ]
     ],
     "slimit": "1",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Processor Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_processor",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Metrics",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_disk",
     "select": [
      [
       { "params": [ "iotime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "iotime" ], "type": "alias" }
      ],
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Processor Consumption (IBM Power)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "aix_processor",
     "select": [
      [
       { "params": [ "physc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "physc" ], "type": "alias" }
      ],
      [
       { "params": [ "lbusy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "lbusy" ], "type": "alias" }
      ],
      [
       { "params": [ "entc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "entc" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Device I/O - Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_disk",
     "select": [
      [
       { "params": [ "read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Device I/O - Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_disk",
     "select": [
      [
       { "params": [ "write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O - Receive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_name ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_network",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O - Transmit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_name ($col)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "base_network",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "base_netstat",
     "select": [
      [
       { "params": [ "ip_conn_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "ip_conn" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp4_conn_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tcp4_active" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp4_conn_passive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tcp4_passive" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp4_conn_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tcp4_reset" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp4_conn_failures" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "tcp4_failures" ], "type": "alias" }
      ],
      [
       { "params": [ "udp4_data_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "udp4_recv" ], "type": "alias" }
      ],
      [
       { "params": [ "udp4_data_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "udp4_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "udp4_data_recv_error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "udp4_recv_err" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Processes - User Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "$tag_name($tag_pid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "query": "SELECT non_negative_difference(sum(last(\"user_time\"),last(\"kernel_time\"))) FROM \"base_process\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "user_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Processes - Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_name($tag_pid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "base_process",
     "query": "SELECT sum(non_negative_derivative(mean(\"user_time\"), 30s), non_negative_derivative(mean(\"user_time\"), 30s))  FROM \"base_process\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "mem_rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "base_memory",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ],
      [
       { "params": [ "paged" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "paged" ], "type": "alias" }
      ],
      [
       { "params": [ "virtual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "virtual" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_mount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mount" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "base_filesystem",
     "query": "SELECT ( last(\"total_bytes\") - last(\"free_bytes\") ) / last(\"total_bytes\") AS \"used\" FROM \"base_filesystem\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"mount\" fill(none)",
     "select": [
      [
       { "params": [ "free_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}